/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_itep_corelib_Driver_NativeDriver */

#ifndef _Included_cn_com_itep_corelib_Driver_NativeDriver
#define _Included_cn_com_itep_corelib_Driver_NativeDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInOKI
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInOKI
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInOLI
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInOLI
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInLQ
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInLQ
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInMP
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInMP
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInEPOSTP
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInEPOSTP
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

/*
 * Class:     cn_com_itep_corelib_Driver_NativeDriver
 * Method:    InnerRemixBmpInEPOSA
 * Signature: ([IIIIJJ[BII)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeDriver_InnerRemixBmpInEPOSA
  (JNIEnv *, jclass, jintArray, jint, jint, jint, jlong, jlong, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
