/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_itep_corelib_Driver_NativeOKIDriver */

#ifndef _Included_cn_com_itep_corelib_Driver_NativeOKIDriver
#define _Included_cn_com_itep_corelib_Driver_NativeOKIDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_itep_corelib_Driver_NativeOKIDriver
 * Method:    InnerRemixBmpInOKI
 * Signature: ([IIIIJJ[B)I
 */
JNIEXPORT jint JNICALL Java_cn_com_itep_corelib_Driver_NativeOKIDriver_InnerRemixBmpInOKI
  (JNIEnv *, jobject, jintArray, jint, jint, jint, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
